In [1]:
import numpy as np

1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type. 

In [2]:
arr = np.array([1.5, 2.6, 3.7])
arr.dtype

dtype('float64')

 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [3]:
arr = np.array([1+6j, 2.5+5j, 45+89j])
arr.dtype


dtype('complex128')

 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [4]:
arr = np.array([1,2,3,4,5,6])
arr = arr.astype(np.float32)
arr.dtype

dtype('float32')

5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [5]:
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)
arr = arr.astype(np.float32)
arr

float64


array([1.5, 2.6, 3.7], dtype=float32)

6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data Type

In [6]:
def array_attributes(arr):
    print(arr.shape)
    print(arr.size)
    print(arr.dtype)

arr = np.array([1.5, 2.6, 3.7])
array_attributes(arr)


(3,)
3
float64


7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [7]:
def array_dimension(arr):
    return arr.ndim

arr = np.array([1.5, 2.6, 3.7])
array_dimension(arr)


1

8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
size in bytes.

In [8]:
def item_size_info(arr):
    return arr.size, arr.nbytes

arr = np.array([1, 2, 3])
size , bytes = item_size_info(arr)
print(f"array size : {size}\n ")
print(f"size of array in bytes : {bytes}")



array size : 3
 
size of array in bytes : 12


9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [9]:
def array_strides(array):
    return array.strides


x = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]], dtype=np.int32)
array_strides(x)

(20, 4)

10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
and strides of the array.

In [10]:
def shape_stride_relationship(array):
    return array.shape, array.strides

x = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]], dtype=np.int32)
shape_stride_relationship(x)

((2, 5), (20, 4))

 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
zeros with `n` elements.

In [11]:
def create_zeros_array(n):
    
    return np.zeros(n,int)
x = 5
create_zeros_array(x)
    
    

array([0, 0, 0, 0, 0])

 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
NumPy array filled with ones of size `rows x cols`.

In [12]:
def create_ones_matrix(x,y):
    return np.ones((x,y),int)
create_ones_matrix(5,6)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
`step`.

In [13]:
def generate_range_array(x,y,z):
    return np.arange(x,y,z)
generate_range_array(1,6,2)


array([1, 3, 5])

14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
(inclusive).

In [14]:
def generate_linear_space(x,y,z):
    return np.linspace(x,y,z)
generate_linear_space(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
identity matrix of size `n x n` using `numpy.eye`.

In [15]:
def create_identity_matrix(n):
    return np.eye(n)
create_identity_matrix(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

16. Write a function that takes a Python list and converts it into a NumPy array.

In [16]:
def list_array(list):
    return np.array(list)
list = [1,2,3,4,5,6]
list_array(list)
    

array([1, 2, 3, 4, 5, 6])

17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the 
same data.

In [17]:
arr = np.array([1,2,34,5,6])
view_array = arr.view()
print(view_array)

[ 1  2 34  5  6]


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [18]:
def concatinate_array(arr1,arr2):
    return np.concatenate((arr1,arr2) ,axis=0)

arr1  = [[1,2],[3,4]]
arr2  = [[5,6]]
concatinate_array(arr1,arr2)

array([[1, 2],
       [3, 4],
       [5, 6]])

19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [19]:

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5], [6]])

concatenated_array = np.concatenate((array1, array2), axis=1)

print(concatenated_array)


[[1 2 5]
 [3 4 6]]


20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [20]:
def vertically_stack_arrays(array_list):
    return np.vstack(array_list)

ar = [1,2,3,4,5,6]
vertically_stack_arrays(ar)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
with a given step size.

In [21]:
def create_numpy_array(start,stop,step):
    
    return np.arange(start,stop+1,step)

create_numpy_array(0,10,2)

array([ 0,  2,  4,  6,  8, 10])

22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
(inclusive).

In [22]:
def linspace_array(start,stop,n):

    return np.linspace(start,stop,n)

linspace_array(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 
1000 (inclusive).

In [23]:
def logspace_array(start,stop,n):

    return np.logspace(start,stop,num=n,endpoint=True)

logspace_array(1,1000,5)

C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpy\core\function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
are random integers between 1 and 100.

In [24]:
import pandas as pd
df = pd.DataFrame(np.random.randint(1,100,5*3).reshape(5,3))
df

0   1   2
0  15   6  41
1  31  71  79
2  93  48  99
3  13  18  55
4  68  62  65

25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
with zeros. Use NumPy operations within the Pandas DataFrame.


In [25]:
def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.maximum(df[column_name], 0)
    return df

data = {
    'A': [1, -2, 3, -4, 5],
    'B': [6, 7, -8, 9, -10]
}
df = pd.DataFrame(data)

# Using the previously defined function
df = replace_negatives_with_zeros(df, 'A')

print(df)


   A   B
0  1   6
1  0   7
2  3  -8
3  0   9
4  5 -10


26. Access the 3rd element from the given NumPy array.


In [26]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [27]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

arr_2d[1][2]

6

28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [28]:
arr = np.array([3, 8, 2, 10, 5, 7])

bool_index = arr >5
arr[bool_index]

array([ 8, 10,  7])

29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[2:6]

array([3, 4, 5, 6])

30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [30]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

arr_2d[0:2,1:]

array([[2, 3],
       [5, 6]])

31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
provided in another array.

In [31]:
def extract_elements(arr2d, indices):

    
    # Ensure the indices array is an np.ndarray
    indices = np.array(indices)
    
    # Extract rows and columns separately
    rows, cols = indices[:, 0], indices[:, 1]
    # print(rows,cols)
    
    # Use advanced indexing to extract the elements
    extracted_elements = arr2d[rows, cols]
    
    return extracted_elements

# Example usage:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

indices = np.array([[0, 1], [1, 2], [2, 0]])

extracted = extract_elements(arr2d, indices)
print(extracted)


[2 6 7]


32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
boolean indexing.

In [32]:
def element_greater_threshold(arr,th):
    greater_array = arr >th

    return arr[greater_array]

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(element_greater_threshold(arr2d,3))
print(element_greater_threshold(arr,3))



[4 5 6 7 8 9]
[4 5 6 7 8 9]


33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
separate arrays for each dimension.

In [33]:
def extract_elements_3d(arr3d, idx1, idx2, idx3):

    # Ensure the indices are NumPy arrays
    idx1 = np.array(idx1)
    idx2 = np.array(idx2)
    idx3 = np.array(idx3)
    
    # Use advanced indexing to extract the elements
    extracted_elements = arr3d[idx1, idx2, idx3]
    
    return extracted_elements

# Example usage:
arr3d = np.array([[[ 1,  2,  3],
                   [ 4,  5,  6],
                   [ 7,  8,  9]],
                  
                  [[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]],
                  
                  [[19, 20, 21],
                   [22, 23, 24],
                   [25, 26, 27]]])

idx1 = [0, 1, 2]
idx2 = [1, 2, 0]
idx3 = [2, 1, 0]

extracted = extract_elements_3d(arr3d, idx1, idx2, idx3)
print(extracted)


[ 6 17 19]


34. Write a NumPy function that returns elements from an array where both two conditions are satisfied 
using boolean indexing.

In [34]:
def extract_elements_with_conditions(arr, condition1, condition2):
    """
    Extract elements from an array where both conditions are satisfied.
    
    Parameters:
    arr (np.ndarray): The input array.
    condition1 (callable): A function representing the first condition.
    condition2 (callable): A function representing the second condition.
    
    Returns:
    np.ndarray: An array of elements that satisfy both conditions.
    """
    # Apply the conditions
    mask = condition1(arr) & condition2(arr)
    
    # Use Boolean indexing to extract the elements
    extracted_elements = arr[mask]
    
    return extracted_elements

# Example usage:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define two conditions
condition1 = lambda x: x > 3
condition2 = lambda x: x < 8

# Extract elements satisfying both conditions
extracted = extract_elements_with_conditions(arr, condition1, condition2)
print(extracted)


[4 5 6 7]


35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
in separate arrays.

In [35]:
def extract_elements_2d(arr2d, row_indices, col_indices):

    # Ensure the indices are NumPy arrays
    row_indices = np.array(row_indices)
    col_indices = np.array(col_indices)
        
    extracted_elements = arr2d[row_indices, col_indices]
    
    return extracted_elements

# Example usage:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

row_indices = [0, 1, 2]
col_indices = [1, 2, 0]

extracted = extract_elements_2d(arr2d, row_indices, col_indices)


36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [36]:
np.random.seed(0)
arr = np.random.randint(1,9,3*3).reshape(3,3)
print(arr)

arr + 5

[[5 8 6]
 [1 4 4]
 [4 8 2]]


array([[10, 13, 11],
       [ 6,  9,  9],
       [ 9, 13,  7]])

37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
corresponding element in arr1 using NumPy broadcasting.

In [37]:
arr1 = np.random.randint(0,9,3).reshape(1,3)
arr2 = np.random.randint(0,9,12).reshape(3,4)

arr = arr1.reshape(3,1) * arr2

arr

array([[12, 21, 18, 24],
       [40,  5, 30, 35],
       [14, 16,  2, 10]])

38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
NumPy broadcasting.

In [38]:
arr1 = np.random.randint(0,9,4).reshape(1,4)
arr2  = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [1,2,3]])

arr1.reshape(4,1) * arr2

array([[ 8, 16, 24],
       [16, 20, 24],
       [21, 24, 27],
       [ 0,  0,  0]])

39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy 
broadcasting.

In [39]:
arr1 = np.random.randint(0,9,3).reshape(3,1)
arr2 = np.random.randint(0,9,3).reshape(1,3)
arr1*arr2





array([[ 6,  9, 24],
       [10, 15, 40],
       [ 0,  0,  0]])

40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
broadcasting. Handle the shape incompatibility.

In [40]:
arr1 = np.random.randint(0,9,3).reshape(3,1)
arr2 = np.random.randint(0,9,3).reshape(1,3)

arr2**arr1

array([[  3,   7,   0],
       [ 27, 343,   0],
       [ 27, 343,   0]])

41. Calculate column wise mean for the given array:

In [41]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

for i in range(0,3):
    print(np.mean(arr[:,i]))


2.5
3.5
4.5


42. Find maximum value in each row of the given array:

In [42]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

for i in range(0,2):
    print(np.max(arr[i]))


3
6


43. For the given array, find indices of maximum value in each column.

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in range(0,2):
    print(np.argmax(arr[i]))



2
2


44. For the given array, apply custom function to calculate moving sum along rows.

In [44]:
def moving_sum(arr):


    for i in range(0,2):
        print(np.sum(arr[i]))

arr = np.array([[1, 2, 3], [4, 5, 6]])
moving_sum(arr)

6
15


45. In the given array, check if all elements in each column are even.

In [45]:
arr = np.array([[2, 4, 6], [3, 5, 7]])


def check_all_even_columns(arr):

    # Check if each element is even
    is_even = (arr % 2 == 0)
    
    # Check if all elements in each column are even
    all_even_columns = np.all(is_even, axis=0)
    
    return all_even_columns

arr = np.array([[2, 4, 6], [3, 5, 7]])

result = check_all_even_columns(arr)
print("Array:")
print(arr)
print("\nAre all elements in each column even?")
print(result)


Array:
[[2 4 6]
 [3 5 7]]

Are all elements in each column even?
[False False False]


46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
reshaped matrix.

In [46]:
def matrix(arr , m , n ):

    size = len(arr)

    if size != m*n:
        return f"array can not reshape due to insufficient element"
    
    return arr.reshape(m,n)

original_array = np.array([1, 2, 3, 4, 5, 6])
matrix(original_array,3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

47. Create a function that takes a matrix as input and returns the flattened array.

In [47]:
def falt_matrix(arr):
    
    return arr.flatten()



input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

falt_matrix(input_matrix)

array([1, 2, 3, 4, 5, 6])

48. Write a function that concatenates two given arrays along a specified axis.

In [48]:
def concat_array(arr1 , arr2 , ax):
    
    return np.concatenate((arr1 ,arr1 ),axis = ax)

arr1  = np.array([[1, 2, 3], [4, 5, 6]])
arr2  = np.array([[1, 2, 3], [4, 5, 6]])

concat_array(arr1,arr2 ,1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

49. Create a function that splits an array into multiple sub-arrays along a specified axis.

In [49]:
def split_array(arr,split,indices):
    return np.array_split(arr,5,1)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

splitArray = split_array(original_array,3,1)

for array in splitArray:
    print(array,'\n')

[[1]
 [4]
 [7]] 

[[2]
 [5]
 [8]] 

[[3]
 [6]
 [9]] 

[] 

[] 



50. Write a function that inserts and then deletes elements from a given array at specified indices.

In [50]:
def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
  
    # Insert elements at specified indices
    modified_array = np.insert(original_array, indices_to_insert, values_to_insert)
    # Delete elements at specified indices
    modified_array = np.delete(modified_array, indices_to_delete)
    return modified_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

insert_and_delete_elements(original_array,indices_to_insert,values_to_insert,indices_to_delete)


array([ 1, 10,  4, 11,  5])

51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
Perform element-wise addition between `arr1` and `arr2`.

In [51]:

arr1 = np.random.randint(1,100,size=10)

arr2 = np.arange(1,11)

result = arr1 + arr2

result


array([67, 12, 61, 37, 37, 81, 31, 44, 85, 66])

52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [52]:
arr1 = np.arange(10,0,-1)
arr2 = np.arange(1,11)

arr2 - arr1

array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9])

53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
Perform element-wise multiplication between `arr1` and `arr2`.

In [53]:
arr1 = np.random.randint(1,100,size=5)

arr2 = np.arange(1,6)

print(arr1,'\n')
print(arr2,'\n')


result = arr1 * arr2

result

[29 35  1  1 37] 

[1 2 3 4 5] 



array([ 29,  70,   3,   4, 185])

54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
to 5. Perform element-wise division of `arr1` by `arr2`.

In [54]:
arr1 = np.random.randint(2 // 2, (10 + 1) // 2, 5) * 2

arr2 = np.arange(1,6)

arr1/arr2


array([4. , 2. , 2. , 0.5, 0.4])

55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [55]:
arr1 = np.arange(1,6)
arr2 = arr1[::-1]

result = np.power(arr1 , arr2)
result



array([ 1, 16, 27, 16,  5])

56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [56]:
import numpy as np

def count_substring_occurrences(array, substring):

    count = 0
    
    for element in np.nditer(array):
        # Check if the element is a string and then count occurrences of substring
        if isinstance(element.item(), str):
            count += element.item().count(substring)    
    return count


arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

substring = "hello"

result = count_substring_occurrences(arr, substring)
print(f"Total occurrences of '{substring}':", result)






Total occurrences of 'hello': 3


57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [57]:
def extract_uppercase(arr):
    cap_array = []
    for word in arr:
        letter_arr = ""
        for letter in word:
            if letter in 'QWERTYUIOPASDFGHJKLZXCVBNM':
                letter_arr += letter
        cap_array.append(letter_arr)
    cap_array = np.array(cap_array)

    return cap_array

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

extract_uppercase(arr)


array(['H', 'W', 'OAI', 'GPT'], dtype='<U3')

58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [58]:
arr

array(['Hello', 'World', 'OpenAI', 'GPT'], dtype='<U6')

In [59]:
def replace_substring(array,old_substring,new_substring):
    modified_array = np.copy(array)
    
    # Iterate through each element in the NumPy array
    for i in np.ndindex(array.shape):
        # Check if the element is a string and then replace occurrences of the old substring
        if isinstance(array[i], str):
            modified_array[i] = array[i].replace(old_substring, new_substring)
    
    return modified_array

array = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = "apple"
new_substring = "goava"
result = replace_substring(array,old_substring,new_substring)
print("Original array:", array)
print("Modified array:", result)

Original array: ['apple' 'banana' 'grape' 'pineapple']
Modified array: ['goava' 'banana' 'grape' 'pinegoava']


59. Write a function that concatenates strings in a NumPy array element-wise.

In [60]:
def concatenate_strings(array):
    concatenated_array = ""
    for i in range(array.size):
        concatenated_array += array[i]


    
    return concatenated_array

arr1 = np.array(['Hello ', 'World '])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1)
result = concatenate_strings(arr2)

print("Concatenated array:", result)


Concatenated array: OpenAI


60. Write a function that finds the length of the longest string in a NumPy array.


In [61]:
def longest_string(arr):
    length = 0
    for i in arr:
        if len(i) > length : 
            length = len(i) 

    return length

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(f"Longest word in array with letters : {longest_string(arr)}")



Longest word in array with letters : 9


 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
standard deviation of the dataset using NumPy's functions.

In [62]:
data = np.random.randint(1,1000,100)
print("mean = ",data.mean())
print("median = ",np.median(data))
print("variance = ",np.var(data))
print("stanard deviation = ",np.std(data))





mean =  515.64
median =  555.5
variance =  92286.27040000001
stanard deviation =  303.78655401449225


 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the 
dataset.

In [63]:
arr=np.random.randint(1,100,50)
percentile=np.percentile(arr,[25,75])
print(" the 25th percentile is: ",percentile[0])
print(" the 75th percentile is: ",percentile[1])

 the 25th percentile is:  22.75
 the 75th percentile is:  71.75


63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
arrays using NumPy's `corrcoef` function.

In [64]:
ls1=[1,2,3,4,5]
ls2=[4,3,2,1,6]
arr1=np.array(ls1)
arr2=np.array(ls2)
coef_mat=np.corrcoef(arr1,arr2)
print(coef_mat[0,1]) # this give the correlation coefficient between arr1 and arr2.

0.1643989873053573


In [65]:
#Q64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))
print(np.dot(arr1,arr2))

[[113 107 121]
 [ 93 101  82]
 [173 155 151]]


In [66]:
#Q65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
# percentiles along with the first and third quartiles.
# we have function np.percentile(arr,[list of number which is numberth percentile])
arr=np.random.randint(10,1000,50)

percentile=np.percentile(arr,[10,50,90])
print(" the 10th percentiles :",percentile[0])
print(" the 50th percentiles :",percentile[1])
print(" the 90th percentiles :",percentile[2])

 the 10th percentiles : 157.0
 the 50th percentiles : 640.0
 the 90th percentiles : 911.0


In [67]:
#Q66. Create a NumPy array of integers and find the index of a specific element.
import numpy as np

def find_element_index(arr, ele):
    
    indices = np.where(arr == ele)[0]
    if indices.size > 0:
        return indices[0]
    else:
        return "Element not found."
arr = np.array([2, 3, 4, 6, 7, 8, 9, 10])
print(arr)
ele = int(input("Enter your element: "))
index = find_element_index(arr, ele)
print(f"The index is: {index}" if isinstance(index, int) else index)

[ 2  3  4  6  7  8  9 10]
Element not found.


In [68]:
#Q67. Generate a random NumPy array and sort it in ascending order.
ls=[1,3,4,5,8,6,2]
arr=np.array(ls)
arr1=np.sort(arr)
print(arr1)

[1 2 3 4 5 6 8]


In [69]:
#Q68. Filter elements >20  in the given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])
arr1=arr[arr>20]
print(arr1)

[25 42 30]


In [70]:
#Q69. Filter elements which are divisible by 3 from a given NumPy array
arr = np.array([1, 5, 8, 12, 15])
arr1=arr[arr%3==0]
print(arr1)

[12 15]


In [71]:
#Q70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
arr1 = arr[(arr>=20) & (arr<=40)]
print(arr1)

[20 30 40]


In [72]:
#Q71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder
arr = np.array([1, 2, 3])
x=arr.dtype.byteorder
print(x)  # it give '='when byteorder of array is 'little' and '|' when byteorder of array is 'big'

=


In [73]:
#Q72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr=np.array([2,3,4,5,6,78,9])
arr1=arr.byteswap()
print(arr1)

[  33554432   50331648   67108864   83886080  100663296 1308622848
  150994944]


In [74]:
#Q73. For the given NumPy array, swap its byte order without modifying the original array using 
# `newbyteorder()`
arr=np.array([1,2,3,4,5,67,8,90])
arr1=arr.newbyteorder()   # byteorder is not callable but newbyteorder is callable.
print(arr1)

[  16777216   33554432   50331648   67108864   83886080 1124073472
  134217728 1509949440]


In [75]:
#Q74.  For the given NumPy array and swap its byte order conditionally based on system endianness using 
# `newbyteorder()`.
import sys
arr = np.array([1, 2, 3], dtype=np.int32)
arr=arr.newbyteorder('big' if sys.byteorder=='little' else 'little') 
# from this function newbyteorder -> we convert one byteorder to another
print(arr)

[16777216 33554432 50331648]


In [76]:
#Q75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
# attribute `byteorder`.
import sys
arr = np.array([1, 2, 3], dtype=np.int32)
byte_swap_needed =  (sys.byteorder=='int32')
if byte_swap_needed:
    print("it is needed")
else:
    print("not needed")  

not needed


In [77]:
#Q76.  Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
ls=[1,2,3,4,5,6,7,8,9,10]
arr=np.array(ls)
# print(arr)
arr1=arr.copy()
print(arr1)
arr1[4]=100
print(arr)
print(arr1)
# don't effect 'arr1'

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4 100   6   7   8   9  10]


In [78]:
#Q77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
arr=np.random.randint(1,10,(3,3))
arr1=arr[1:,1:]
arr1[0][1]=10
arr1[1][1]=1000
print(arr1)
print(arr)

[[   3   10]
 [   2 1000]]
[[   8    8    6]
 [   2    3   10]
 [   9    2 1000]]


In [79]:
#Q78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
ls=[i for i in range(1,13)]
arr=np.array(ls)
arr1=arr.reshape((4,3))
arr2=arr1[1]
print(arr2+5)
print(arr1)
# not effected

[ 9 10 11]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [80]:
#Q79.  Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
# reflects changes in the original `orig_array`.
ls=[i for i in range(1,9)]
arr=np.array(ls)
arr1=arr.reshape((2,4))
arr2=arr1.reshape((4,2))
print(arr2)
arr2[3][1]=100
arr2[2][1]=20
print(arr2)
print(arr1)
# affected arr1

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[  1   2]
 [  3   4]
 [  5  20]
 [  7 100]]
[[  1   2   3   4]
 [  5  20   7 100]]


In [81]:
#Q80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
arr=np.random.randint(1,20,(3,4))
print(arr)
arr1=arr[arr>5]
print(arr1)
arr1[5]=21
arr1[4]=26
print(arr1)
print(arr)
# not effected

[[ 9  5  1 12]
 [ 3  6 17  9]
 [ 2 18 17  4]]
[ 9 12  6 17  9 18 17]
[ 9 12  6 17 26 21 17]
[[ 9  5  1 12]
 [ 3  6 17  9]
 [ 2 18 17  4]]


In [82]:
#81.  Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
# operations between them.
import numpy.matlib as nm 
arr1=nm.random.randint(1,10,(3,3))
arr2=nm.random.randint(1,10,(3,3))
print(arr1+arr2)
print(arr1-arr2)

[[11 11  8]
 [ 7  6  7]
 [14 10  9]]
[[ 7  7  2]
 [ 3 -4  1]
 [ 2 -2 -3]]


In [83]:
#Q82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication
arr1=nm.random.randint(1,10,(3,2))
arr2=nm.random.randint(1,10,(2,4))
print(nm.dot(arr1,arr2))

[[ 33  60  27  18]
 [ 72 112  48  40]
 [ 53  68  27  30]]


In [84]:
#Q83. Create a matrix `E` and find its transpose
arr1=nm.random.randint(1,10,(3,3))
print(arr1)
print(arr1.T)

[[2 1 7]
 [1 5 9]
 [5 4 4]]
[[2 1 5]
 [1 5 4]
 [7 9 4]]


In [85]:
#Q84. Generate a square matrix `F` and compute its determinant
arr=nm.random.randint(1,10,(3,3))
print(arr)
print(np.linalg.det(arr))

[[9 9 8]
 [1 4 9]
 [8 8 2]]
-137.99999999999994


In [86]:
#Q85. Create a square matrix `G` and find its inverse.
arr=nm.random.randint(1,10,(3,3))
print(np.linalg.inv(arr))

[[-0.07692308 -0.19230769  0.26923077]
 [-0.03076923  0.22307692  0.00769231]
 [ 0.23076923  0.07692308 -0.30769231]]
